## numpy

In [13]:
import numpy as np

In [14]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

## Creating array from list

In [15]:
a= np.array([1,2,3,4,5])
b= np.array([7,8,9,10,11])
c = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
print(f'1D array: {a}\n{b}\n2D array: {c}')

1D array: [1 2 3 4 5]
[ 7  8  9 10 11]
2D array: [[1 2 3]
 [4 5 6]]


## Indexing & Slicing

In [17]:
print(a[0]+b[0])

8


In [18]:
print(f'2nd element of 2nd row: {c[1, 1]}')

2nd element of 2nd row: 5


In [19]:
print(a[1:])

[2 3 4 5]


In [20]:
print(b[-3:-1])

[ 9 10]


## list vs numpy array

In [24]:
list= [1,2,3]
print("Python list multiplication: ", list*2)

np_array= np.array([1,2,3]) #element wise multiplication
print("Python array multiplication: ", np_array*2)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]


## creating array from scratch

In [33]:
zeros = np.zeros((3, 3))
print("Zeroes array: \n", zeros)

ones = np.ones((3, 3))
print("Ones array: \n", ones)

full= np.full((3,3), 7)
print("Full array: \n", full)

random= np.random.random((2,3))
print("Random array: \n", random)

sequence= np.arange(0, 10, 2)
print("Sequence array: \n", sequence)

Zeroes array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random array: 
 [[0.12489214 0.22663707 0.80967452]
 [0.38928117 0.80374433 0.81155855]]
Sequence array: 
 [0 2 4 6 8]
