## numpy


In [ ]:
import numpy as np
np.array((1, 2, 3, 4, 5))

array([1, 2, 3, 4, 5])

## Creating array from list


In [38]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([7, 8, 9, 10, 11, 12])
c = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(f'1D array: {a}\n{b}\n2D array: {c}')

1D array: [1 2 3 4 5]
[ 7  8  9 10 11 12]
2D array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Indexing & Slicing


In [ ]:
'''a= np.array([1,2,3,4,5])
b= np.array([7,8,9,10,11,12])
c = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])'''

print(a[0]+b[0])
print(a[1:5])
print(a[1:])
print("Negative indexing:", b[-4:-1])
print("With step: ", b[1:5:2])

# for 2d array
print("\n2nd element of 2nd row: ", c[1][1])
print("2nd element of 3rd row: ", c[2][1])
print("Entire row 2: ",c[2])
print("Entire column 3: ",c[:, 2]) #c[(entire row): 2]




8
[2 3 4 5]
[2 3 4 5]
Negative indexing: [ 9 10 11]
With step:  [ 8 10]

2nd element of 2nd row:  5
2nd element of 3rd row:  8
Entire row 2:  [7 8 9]
Entire column 3:  [3 6 9]


## list vs numpy array


In [ ]:
list = [1, 2, 3]
print("Python list multiplication: ", list*2)

np_array = np.array([1, 2, 3])  # element wise multiplication
print("Python array multiplication: ", np_array*2)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]


## creating array from scratch


In [ ]:
zeros = np.zeros((3, 3))
print("Zeroes array: \n", zeros)

ones = np.ones((3, 3))
print("Ones array: \n", ones)

full = np.full((3, 3), 7)
print("Full array: \n", full)

random = np.random.random((2, 3))
print("Random array: \n", random)

sequence = np.arange(0, 10, 2)
print("Sequence array: \n", sequence)

Zeroes array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random array: 
 [[0.5791245  0.90430522 0.7898406 ]
 [0.00771636 0.38612861 0.40281529]]
Sequence array: 
 [0 2 4 6 8]
