In [17]:
import numpy as np

In [18]:
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [19]:
a= np.array([1,2,3,4,5])
b= np.array([7,8,9,10,11])
c = np.array([[1, 2, 3], [4, 5, 6]])

In [20]:
print(f'{a}\n{b}\n{c}')

[1 2 3 4 5]
[ 7  8  9 10 11]
[[1 2 3]
 [4 5 6]]


In [21]:
print(a[0]+b[0])

8


In [22]:
print(f'2nd element of 2nd row: {c[1, 1]}')

2nd element of 2nd row: 5


In [23]:
print(a[1:])

[2 3 4 5]


In [24]:
print(b[-3:-1])

[ 9 10]
