## Advance Operation


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# data strucutre: [restauren_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # kacchi vai
    [2, 120000, 140000, 160000, 190000],  # kacchi dine
    [3, 200000, 230000, 260000, 300000],  # sultan dine's
    [4, 180000, 210000, 240000, 270000],  # chillox
    [5, 160000, 185000, 205000, 230000],  # pizzaburg
])

print("=== FOODPANDA ===")

print("\nSales data Shape:", sales_data.shape)

print("\nData for the 1st 3 restaurent:\n", sales_data[0:3])

# : -> ALL rows && 1: -> start from column index 1 until the end.
print("\nData for the 1st 3 restaurent without indexing:\n", sales_data[:, 1:])

print("\nTotal sales per year:")
yearly_sale= np.sum(sales_data[:, 1:], axis=0)
print(yearly_sale)

print("\nMinimun sales per restaurant:")
min_sales= np.min(sales_data[:, 1:], axis=1)
print(min_sales)

print("\nMaximun sales per year:")
max_sales= np.max(sales_data[:, 1:], axis=0)
print(max_sales)

print("\nAverage sales per restaurant:")
avg_sales= np.mean(sales_data[:, 1:], axis=1)
print(avg_sales)

=== FOODPANDA ===

Sales data Shape: (5, 5)

Data for the 1st 3 restaurent:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

Data for the 1st 3 restaurent without indexing:
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]

Total sales per year:
[ 810000  945000 1085000 1240000]

Minimun sales per restaurant:
[150000 120000 200000 180000 160000]

Maximun sales per year:
[200000 230000 260000 300000]

Average sales per restaurant:
[200000. 152500. 247500. 225000. 195000.]
