## Advance Operation


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# data strucutre: [restauren_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 25000],  # kacchi vai
    [2, 120000, 140000, 160000, 19000],  # kacchi dine
    [3, 200000, 230000, 260000, 30000],  # sultan dine's
    [4, 180000, 210000, 240000, 27000],  # chillox
    [5, 160000, 185000, 205000, 23000],  # pizzaburg
])

print("=== FOODPANDA ===")

print("\nSales data Shape:", sales_data.shape)

print("\nData for the 1st 3 restaurent:\n", sales_data[0:3])

# : -> ALL rows && 1: -> start from column index 1 until the end.
print("\nData for the 1st 3 restaurent without indexing:\n", sales_data[:, 1:])

=== FOODPANDA ===

Sales data Shape: (5, 5)

Data for the 1st 3 restaurent:
 [[     1 150000 180000 220000  25000]
 [     2 120000 140000 160000  19000]
 [     3 200000 230000 260000  30000]]

Data for the 1st 3 restaurent:
 [[150000 180000 220000  25000]
 [120000 140000 160000  19000]
 [200000 230000 260000  30000]
 [180000 210000 240000  27000]
 [160000 185000 205000  23000]]
